@tool
class_name EditorToolsStatsEnumGenerator
extends RefCounted

const STAT_DATA_GD_FILE_PATH: String = "res://autoloads/stats/stat_data.gd"
const IGNORED_STAT_DATA_PROPERTIES: Array = [
	"RefCounted",
	"Resource",
	"resource_local_to_scene",
	"resource_path",
	"resource_name",
	"resource_scene_unique_id",
	"script",
	"stat_data.gd",
]
const AUTOGENERATED_WARNING: String = "This file was generated with EditorToolsStatsEnumGenerator. Any manual modifications to it will be overwritten!"
const OUTPUT_ENUM_FILE_PATH: String = "res://autoloads/stats/stat_data_enum.gd"
const OUTPUT_ENUM_CLASS_NAME: String = "StatDataEnum"
const REGENERATE_ENUMS_COMMAND_PALETTE_NAME: String = "Regenerate Stats Enum"
const REGENERATE_ENUMS_COMMAND_PALETTE_PATH: String = "editor_tools/regenerate_stats_enum"
const REGENERATE_ENUMS_FUNC_NAME: String = "_regenerate_enums"

static var _instance: EditorToolsStatsEnumGenerator

static func get_instance() -> EditorToolsStatsEnumGenerator:
	if _instance == null:
		_instance = EditorToolsStatsEnumGenerator.new()
	return _instance

func initialize() -> void:
	var editor_tools: EditorToolsEditorPlugin = EditorToolsEditorPlugin.get_instance()
	if not editor_tools.resource_saved.is_connected(_on_resource_saved):
		editor_tools.resource_saved.connect(_on_resource_saved)
	EditorInterface.get_command_palette().add_command(REGENERATE_ENUMS_COMMAND_PALETTE_NAME, REGENERATE_ENUMS_COMMAND_PALETTE_PATH, Callable(self, REGENERATE_ENUMS_FUNC_NAME))

func deinitialize() -> void:
	var editor_tools: EditorToolsEditorPlugin = EditorToolsEditorPlugin.get_instance()
	if editor_tools.resource_saved.is_connected(_on_resource_saved):
		editor_tools.resource_saved.disconnect(_on_resource_saved)
	EditorInterface.get_command_palette().remove_command(REGENERATE_ENUMS_COMMAND_PALETTE_PATH)
	_instance = null

func _on_resource_saved(resource: Resource) -> void:
	if resource.resource_path.get_extension() != "gd":
		return
	if resource.resource_path != STAT_DATA_GD_FILE_PATH:
		return
	_regenerate_enums()

func _regenerate_enums() -> void:
	var enum_names: Array[String] = _get_enum_names()
	var file_access: FileAccess = FileAccess.open(OUTPUT_ENUM_FILE_PATH, FileAccess.ModeFlags.WRITE)
	file_access.store_line("# %s" % AUTOGENERATED_WARNING)
	file_access.store_line("class_name %s" % OUTPUT_ENUM_CLASS_NAME)
	file_access.store_line("const VALUES: String = \"\\")
	for enum_name in enum_names:
		file_access.store_line("%s,\\" % enum_name)
	file_access.store_line("\"")
	file_access.close()
	print("EditorToolsStatsEnumGenerator: Regenerated enums at '%s'." % OUTPUT_ENUM_FILE_PATH)

func _get_enum_names() -> Array[String]:
	var stat_data_temp: StatData = StatData.new()
	var property_list: Array[Dictionary] = stat_data_temp.get_property_list()
	var enum_names: Array[String] = []
	for property in property_list:
		var property_name: String = property["name"]
		if property_name in IGNORED_STAT_DATA_PROPERTIES:
			continue
		enum_names.append(property_name)
	return enum_names
